version: '3.8'

services:
  backend:
    build: ./backend
    restart: always
    environment:
      - MONGO_URL=mongodb://mongodb:27017/
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    networks:
      - app-network

  mongo:
    image: mongo:5.0
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local