name: CD

on:
  push:
    tags:
      - 'mvp_v*'
      - 'v*.*.*'

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/main'
    name: 🚀 Deploy to Staging
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH & deploy
        run: |
          ssh -o StrictHostKeyChecking=no \
            ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
              cd /home/innoalias
              git pull origin main
              docker-compose pull
              docker-compose up -d
              docker image prune -f
            EOF

  deploy-production:
    if: startsWith(github.ref, 'refs/tags/v')
    name: 🚀 Deploy to Production
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH & deploy
        run: |
          ssh -o StrictHostKeyChecking=no \
            ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
              cd /home/innoalias
              git pull origin main
              docker-compose pull
              docker-compose up -d
              docker image prune -f
            EOF
