name: CD

on:
  push:
    tags:
      - 'mvp_v*'

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy-production:
    if: startsWith(github.ref, 'refs/tags/mvp_v')
    name: 🚀 Deploy to Production
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
      - run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | sed 's/\r$//' > key
          chmod 600 key
          eval "$(ssh-agent -s)"
          ssh-add key

      - name: SSH & deploy
        run: |
          ssh -o StrictHostKeyChecking=no \
            ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
              cd /home/innoalias
              git pull origin main
              docker-compose pull
              docker-compose up -d
              docker image prune -f
            EOF
